/** @type {import('tailwindcss').Config} */
module.exports = {
  // important: true,
  content: ['./pages/**/*.{js,ts,jsx,tsx}', './components/**/*.{js,ts,jsx,tsx}'],
  corePlugins: {
    preflight: true,
  },
  theme: {
    backgroundColor: {
      primary: 'var(--primary-pink)',
      white: 'var(--white)',
      skintone: 'var(--skintone)',
      blue: 'var(--blue)',
      green: 'var(--green)',
      transparent: 'transparent',
      'orange-100': 'var(--black-100)',
      'black-100': 'var(--black-100)',
      'black-200': 'var(--black-200)',
      'grey-100': 'var(--grey-100)',
      'grey-200': 'var(--grey-200)',
      'grey-300': 'var(--grey-300)',
      'grey-400': 'var(--grey-400)',
      'grey-500': 'var(--grey-500)',
      'red-100': 'var(--red-100)',
      'red-200': 'var(--red-200)',
      'purple-100': 'var(--purple-100)',
      'purple-200': 'var(--purple-200)',
    },
    backgroundImage: {
      'linear-gradient-100': 'var(--linear-gradient-100)',
      'linear-gradient-200': 'var(--linear-gradient-200)',
      'linear-gradient-300': 'var(--linear-gradient-300)',
      'linear-radial-100': 'var(--linear-radial-100)',
      'linear-radial-200': 'var(--linear-radial-200)',
      'linear-radial-300': 'var(--linear-radial-300)',
    },
    textColor: {
      primary: 'var(--primary-pink)',
      white: 'var(--white)',
      skintone: 'var(--skintone)',
      blue: 'var(--blue)',
      green: 'var(--green)',
      'orange-100': 'var(--black-100)',
      'black-100': 'var(--black-100)',
      'black-200': 'var(--black-200)',
      'grey-100': 'var(--grey-100)',
      'grey-200': 'var(--grey-200)',
      'grey-300': 'var(--grey-300)',
      'grey-400': 'var(--grey-400)',
      'grey-500': 'var(--grey-500)',
      'red-100': 'var(--red-100)',
      'red-200': 'var(--red-200)',
      'purple-100': 'var(--purple-100)',
      'purple-200': 'var(--purple-200)',
    },
    borderColor: {
      primary: 'var(--primary-pink)',
      white: 'var(--white)',
      skintone: 'var(--skintone)',
      blue: 'var(--blue)',
      green: 'var(--green)',
      'orange-100': 'var(--black-100)',
      'black-100': 'var(--black-100)',
      'black-200': 'var(--black-200)',
      'grey-100': 'var(--grey-100)',
      'grey-200': 'var(--grey-200)',
      'grey-300': 'var(--grey-300)',
      'grey-400': 'var(--grey-400)',
      'grey-500': 'var(--grey-500)',
      'red-100': 'var(--red-100)',
      'red-200': 'var(--red-200)',
      'purple-100': 'var(--purple-100)',
      'purple-200': 'var(--purple-200)',
    },
    extend: {
      fontFamily: {
        roboto: 'var(--font-sans)',
      },
      screens: {
        'm-s': { max: '375px' },
        'm-xs': { max: '744px' },
        'm-md': { max: '950px' },
        'm-lg': { max: '1128px' },
        'm-xl': { max: '1440px' },
      },
    },
  },
  plugins: [],
};
