export const ME_KEY = "me"
export const SEARCH_KEY = "search"
export const ROOM_LIST_KEY = "room-list"
export const ROOM_LOCATION_KEY = "room-location"
export const ROOM_DETAIL_KEY = "room-detail"
export const LOCATION_LIST_KEY = "location-list"
